name: Animal Language CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Force a newer Go version to be used
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
          check-latest: true
          cache: true

      - name: Verify Go installation
        run: |
          go version
          echo "GOPATH=$GOPATH"
          echo "GOROOT=$GOROOT"

      # Make sure we're using Go modules
      - name: Setup Go modules
        run: |
          if [ ! -f go.mod ]; then
            echo "Creating go.mod file"
            go mod init animal
          fi
          # Check module configuration
          cat go.mod

      # Set up proper workspace for older Go compatibility
      - name: Set up workspace
        run: |
          # Create GOPATH structure if needed
          mkdir -p $HOME/go/src/animal
          # Copy code to correct location
          cp -r * $HOME/go/src/animal/
          # Set GOPATH
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "Added to GITHUB_ENV: GOPATH=$HOME/go"

      - name: Run tests with coverage
        run: |
          cd $HOME/go/src/animal
          # Run tests with full paths
          go test -v ./core/... ./tests/... ./tests/interpreter/... -coverprofile=coverage.out || true

      - name: Show coverage summary
        run: |
          cd $HOME/go/src/animal
          if [ -f coverage.out ]; then
            go tool cover -func=coverage.out
          else
            echo "No coverage file generated, skipping coverage report"
          fi
