name: Animal Language CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20, 1.21, 1.22, 1.23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests with coverage
        run: |
          go test $(go list ./... | grep -vE '/(wasm|cmd)') -v -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out

      - name: Run static analysis (go vet)
        run: go vet ./...
