name: Animal Language CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18, 1.19, 1.20]

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Debug environment
        run: |
          go version
          go env
          ls -la
          echo "Current directory: $(pwd)"
          echo "Go executable: $(which go)"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug after checkout
        run: |
          ls -la
          echo "Current directory: $(pwd)"
          echo "Go executable: $(which go)"

      - name: Manual module initialization
        run: |
          if [ ! -f go.mod ]; then
            echo "Creating go.mod manually"
            echo "module animal" > go.mod
            echo "go 1.18" >> go.mod
          else
            echo "go.mod exists:"
            cat go.mod
          fi

      - name: Run tests with coverage
        run: |
          go test ./core/... ./tests/... ./tests/interpreter/... -v -coverprofile=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out

      - name: Static analysis (go vet)
        run: go vet ./...