name: Animal Language CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20, 1.21, 1.22, 1.23]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Print Go version (debug)
        run: go version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize go.mod (only if missing)
        run: |
          if [ ! -f go.mod ]; then
            go mod init animal
          fi
          go mod tidy

      - name: Run tests with coverage
        run: |
          go test ./core/... ./tests/... ./tests/interpreter/... -v -coverprofile=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out

      - name: Run static analysis (go vet)
        run: go vet ./...
